---

all:
  vars:     # variable for users in the target machines which ansible is using for run command with sudo
    ansible_user: '{{ ssh_user }}'                # Don't change, add value in significant task vars .yml file
    ansible_become_pass: '{{ user_sudo_pass }}'   # Don't change, add value in significant task vars .yml file
    ansible_become: yes
    ansible_become_method: sudo
  children:
    EnvironmentTest:      # Test Environment hosted on azure cloud
      children:
        ProfittoTest:
            172.26.134.7
            172.26.134.8
        CMSTest:
          hosts:
            CMSTest-6:
              ansible_host: 172.26.134.6
        GatewayTest:
          hosts:
            GatewayTest-5:
              ansible_host: 172.28.134.5
        ONLTest:
          hosts:
            ONLTest-5:
              ansible_host: 172.26.134.5
        NONLTest:
          hosts:
            NONLTest-6:
              ansible_host: 172.26.134.6