---

all:
  vars:     # variable for users in the target machines which ansible is using for run command with sudo
    ansible_user: '{{ ssh_user }}'                # Don't change, add value in significant task vars .yml file
    ansible_become_pass: '{{ user_sudo_pass }}'   # Don't change, add value in significant task vars .yml file
    ansible_become: yes
    ansible_become_method: sudo
  children:
    environment-test:      # hosted on azure cloud
      children:
        profitto-test:
          hosts:
            172.26.134.7
            172.26.134.8               
        cms-test:
          hosts:
            172.26.134.6
        gateway-test:
          hosts:
            172.28.134.5
        online-test:
          hosts:
            172.26.134.5
        nearonline-test:
          hosts:
            172.26.134.6