---
- hosts: all
  vars_files:
    - new-input.yml
  gather_facts: yes
  tasks:
    - name: Here we are checking ansible_hostname
      command: echo {{ ansible_hostname }}
    - name: Here we are checking inventory_hostname
      command: echo {{ inventory_hostname }}