---
- hosts: all
  vars_files:
    - new-input.yml
  gather_facts: yes
  tasks:
    - name: Here we are checking ansible_hostname
      debug:
        msg: "hostname is {{ ansible_hostname }}"

    - name: Here we are checking inventory_hostname
      debug:
        msg: "hostname is {{ inventory_hostname }}"

    - name: Here we are checking ansible_host
      debug:
        msg: "hostname is {{ ansible_host }}"
        
    - name: Here we are checking inventory_host
      debug:
        msg: "hostname is {{ inventory_host }}"