---
- hosts: all
  vars_files:
    - new-input.yml
  gather_facts: yes
  tasks:
    - name: Here we are checking ansible_hostname
      debug:
        msg:
          - host IP is {{ ansible_host }}
          - hostname is {{ ansible_hostname }}
          - machine name in hosts file is {{ inventory_hostname }}