---
- hosts: all
  vars_files:
    - new-input.yml
  gather_facts: yes
  tasks:
    - name: Here we are checking ansible_hostname
      debug:
        msg:
         "hostname is {{ ansible_hostname }} \
          machine name is {{ inventory_hostname }} \
          host IP is {{ ansible_host }}"