---

- name: Testing connection before starting
  vars_files:
    - inventory/infra-vars.yml
    - inventory/wls-vars.yml
    - inventory/secrets.yml
    - new-input.yml
  hosts: all
  roles:
    - role: connection-check
  tags:
    - connection-check

- name: Prepare Linux server with needed packages
  vars_files:
    - inventory/infra-vars.yml
    - inventory/wls-vars.yml
    - inventory/secrets.yml
    - new-input.yml
  hosts: all
  roles:
    - role: linux-wls
  tags:
    - prep-os

- name: Copy JDK
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
    - new-input.yml
  hosts: all
  become: true
  become_user: '{{ oracle_user }}'
  roles:
    - role: cp-jdk-package
  tags:
    - cp-jdk

- name: Copy weblogic-fmw packages
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
    - new-input.yml
  hosts: all
  become: true
  become_user: '{{ oracle_user }}'
  roles:
    - role: cp-fmw-package
  tags:
    - cp-fmw

- name: Extract and Install Java
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
  hosts: all
  become: true
  become_user: '{{ oracle_user }}'
  roles:
    - role: linux-jdk
  tags:
    - install-jdk

- name: Install Weblogic
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
  hosts: all
  become: true
  become_user: '{{ oracle_user }}'
  roles:
    - role: fmw-software
  tags:
    - install-fmw

- name: Create DB repo & Create Domain & Start Machine
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
  hosts: all
  become: true
  become_user: '{{ oracle_user }}'
  roles:
    - role: fmw-domain
  tags:
    - fmw-domain

- name: Create managed servers
  vars_files:
    - infra-vars.yml
    - wls-vars.yml
    - secrets.yml
  hosts: all
  become: true
  become_user: '{{ oracle_user }}'
  roles:
    - role: fmw-managed-server
  tags:
    - fmw-server