

# Oracle os user and group
oracle_user: 'oracle'
oracle_group: 'oinstall'

# JDK installer and target folder
jdk_installation_archive: 'jdk-8u172-linux-x64.tar.gz'

# fmw installer
mw_installer: 'fmw_12.2.1.3.0_infrastructure.jar'

# Weblogic
weblogic_admin: 'weblogic'
weblogic_version: '12.2.1.3.0'

# Domain Name
domain_name: 'ValU_domain'

# Nodemanager
node_manager_listen_address: '{{ server_hostname }}'
nodemanager_username: 'weblogic'
node_manager_listen_port: '5556'

# Admin Server
admin_server_hostname: '{{ server_hostname }}'
admin_server_name: 'AdminServer'
admin_server_port: '7001'

# Managed server
managed_server_1_name: 'ValU_server'
managed_server_1_port: '7010'


# Server Hostname
server_hostname: '{{ inventory_hostname }}'