################################################################################
# ==> Tasks for linux-wls Role for configure a RHEL 7 system with requirements 
# ==> for Fusion Middleware infrastructrure installation.
# ==> ValU DevOps
# ==> Ahmed Fadel
################################################################################

# ==> Configure Linux
- name: Install required libraries
  yum: name="{{ packages_list }}" state=present
- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewall Deamon (firewalld)
  service: name=firewalld state=stopped enabled=no
- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: "{{ kernel_params }}"

# ==> Create user and groups
- name: Create groups
  group: name={{ oracle_group }} state=present
- name: Create user
  user: name={{ oracle_user }} groups={{ oracle_group }} password={{ oracle_os_user_pass }}
  
# ==> Add open file and process limits for oracle user
- name: Add soft limit number of open files
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} soft  nofile  {{ soft_no_file }}'
- name: Add hard limit for number of open files
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} hard  nofile  {{ hard_no_file }}'
- name: Add soft limit for number of processes
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} soft  nproc   {{ soft_nproc }}'
- name: Add hard limit for number of processes
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} hard  nproc   {{ hard_nproc }}'
- name: Create a shell profile with file and process limits for oracle user
  template: src=oracle-limits.sh dest=/etc/profile.d/

# ==> Create Base Directories

- name: Create Oracle Base
  file: state=directory path={{ oracle_base }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create jdk folder
  file: state=directory path={{ jdk_folder }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create middleware home
  file: state=directory path={{ middleware_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create middleware common home
  file: state=directory path={{ middleware_common_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: weblogic home
  file: state=directory path={{ weblogic_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create Applications Home directory
  file: state=directory path={{ applications_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create mw installer folder
  file: state=directory path={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create nodemanager home
  file: state=directory path={{ nodemanager_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create Domains Home directory
  file: state=directory path={{ domains_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Create domain home
  file: state=directory path={{ domain_home }} owner={{ oracle_user }} group={{ oracle_group }}


- name: Export needed vars
  shell: |
    export ORACLE_BASE='{{ oracle_base }}'
    export MW_HOME='{{ middleware_home }}'
    export ORACLE_HOME=$MW_HOME
    
    export WLS_HOME='{{ weblogic_home }}'
    export WL_HOME=$WLS_HOME
    
    export DOMAINS_HOME='{{ domains_home }}'
    export DOMAIN_BASE=$DOMAINS_HOME
    export DOMAIN_HOME='{{ domain_home }}'
    
    export JAVA_HOME='{{ jdk_folder }}'
    export PATH=$JAVA_HOME/bin:$PATH
    
    export DISPLAY=localhost:10.0
